### ISSUE TITLE
UnsupportedBrowserError: This OS / browser has one or more missing features preventing it from working correctly (httpProtocol)

### ISSUE THREAD

**Issue by tomdebie** [Scandit/barcodescanner-sdk-for-web-samples#21]
Hello,

I'm trying to test out the barcode scanner for web sdk examples using a trial key.
Unfortunately, I'm running into an UnsupportedBrowserError as soon as the page loads. Currently running Chrome 97.0.4692.99 on windows 10 20H2.
I must be doing something wrong here because the documentation specifies that it runs on any modern browser.

barcodescanner-sdk-for-web-samples-master\vanilla-samples\simple\index.html
Only changed the license key placeholder

Kind regards.
Tom

**Comment by ScanditSupport** [comment]
Hi @tomdebie, 

your issue seems to be related to the specific OS/browser combination you are using.

Can you please reach out to us directly with a full log from the console so that we can look into it?

Submit a request – Frequently Asked Questions (FAQ): https://support.scandit.com/hc/en-us/requests/new.
